server:
  port: 8090

spring:
  application:
    name: api-gateway
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak-provider:
#            issuer-uri: http://localhost:8089/realms/account-realm
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      default-filters:
#        - TokenRelay
      routes:
        - id: api-user
          uri: lb://api-user
          predicates:
            - Path=/users/**
        - id: api-event
          uri: http://localhost:8087
          predicates:
            - Path=/event/**
        - id: api-company
          uri: lb://api-company
          predicates:
            - Path=/company/**
info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enable: true
    endpoints:
      web:
        exposure:
          include: gateway
