server:
  port:
    8089

spring:
  application:
    name: api-security
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enable: true
info:
  app:
    name: ${spring.application.name}
